name: Netflix
options:
  bundleIdPrefix: com.yourname
targets:
  Netflix:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources:
      - Netflix/Netflix
    settings:
      INFOPLIST_FILE: Netflix/Netflix/Info.plist
      CODE_SIGNING_ENTITLEMENTS: Netflix/Netflix/Netflix.entitlements
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
